baseURL = 'https://blog.ifurther.app/'
languageCode = 'zh-tw'
title = 'ifurther Site'
theme = 'gokarna'
defaultContentLanguage = "zh-tw"
#defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
#languageCode = "en"


  [[menu.main]]
    # Display name
    name = "文章"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    # Unique identifiers are required for menu entries without a name property,
    # or for menu entries which re-use a name
    identifier = "github"

    # Absolute URL to external resource
    url = "https://github.com/ifurther"
    weight = 3
	
    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
    pre = "<span data-feather='github'></span>"
    post = ""

  #[[menu.main]]
    #identifier = "en"
    #name = "English"
    #url = "/en/"
    #weight = 5
  #[[menu.main]]	
    #identifier = "zh-cn"
    #name = "简体中文（中国）"
    #url = "/zh-cn/"
    #weight = 4
	
  [params]
    togglePreviousAndNextButtons = true
	defaultContentLanguageInSubdir = false
    defaultContentLanguage = "zh-tw"

  [languages]
    [languages.en]
      disabled = false
      languageCode = ''
      languageDirection = ''
      languageName = ''
      title = ''
      weight = 1
	  contentDir = 'content/en'
	[languages.zh-tw]
	  weight = 0
	  languageName = "正體中文（台灣）"
	  languageCode = "zh-tw"
	  contentDir = 'content/zh-tw'
	[languages.zh-cn]
	  languageName = "简体中文（中国）"
      languageCode = "zh-cn"
	  weight = 3
	  contentDir = 'content/zh-cn'
	[languages.zh-hk]
      languageName = "繁体中文（香港）"
      languageCode = "zh-hk"
	  weight = 2